# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BSSIDApple.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x42SSIDApple.proto\x12\x0e\x62ssid_location\"\xc0\x01\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x01(\x03\x12\x0b\n\x03lon\x18\x02 \x01(\x03\x12\x0c\n\x04unk1\x18\x03 \x01(\x03\x12\x0c\n\x04unk2\x18\x04 \x01(\x03\x12\x0c\n\x04unk3\x18\x05 \x01(\x03\x12\x0c\n\x04unk4\x18\x06 \x01(\x03\x12\x0c\n\x04unk5\x18\x07 \x01(\x03\x12\x0c\n\x04unk6\x18\x08 \x01(\x03\x12\x0c\n\x04unk7\x18\t \x01(\x03\x12\x0c\n\x04unk8\x18\n \x01(\x03\x12\x0c\n\x04unk9\x18\x0b \x01(\x03\x12\r\n\x05unk10\x18\x0c \x01(\x03\x12\r\n\x05unk11\x18\r \x01(\x03\"E\n\x08\x42SSIDGeo\x12\r\n\x05\x62ssid\x18\x01 \x02(\t\x12*\n\x08location\x18\x02 \x01(\x0b\x32\x18.bssid_location.Location\"s\n\x0cWiFiLocation\x12\x0c\n\x04unk1\x18\x01 \x01(\x03\x12&\n\x04wifi\x18\x02 \x03(\x0b\x32\x18.bssid_location.BSSIDGeo\x12\x0c\n\x04unk2\x18\x03 \x01(\x05\x12\x0e\n\x06single\x18\x04 \x01(\x05\x12\x0f\n\x07\x41PIName\x18\x05 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BSSIDApple_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATION._serialized_start=37
  _LOCATION._serialized_end=229
  _BSSIDGEO._serialized_start=231
  _BSSIDGEO._serialized_end=300
  _WIFILOCATION._serialized_start=302
  _WIFILOCATION._serialized_end=417
# @@protoc_insertion_point(module_scope)
